In [ ]:
# import pandas as pd
# sub=pd.read_csv('../input/pa_subtitles.csv')
# sub

In [ ]:
# len(sub)
# 105637/7

In [ ]:
# %%time
# import datetime
# for i in range(sub.shape[0]//7):
#     if i%100==0:
#         print(i)
#     for j in range(7):
#         sub['start'][i+j*15091] = datetime.datetime.strptime(sub['start'][i+j*15091], '%H:%M:%S.%f').time() 
#         sub['end'][i+j*15091]=datetime.datetime.strptime(sub['end'][i+j*15091], '%H:%M:%S.%f').time() 
#         sub['date'][i+j*15091]=datetime.datetime.strptime(sub['date'][i+j*15091], '%Y-%m-%d').date()

# sub.to_csv('pa_subtitles.csv',mode='a',index=False,header=False)


In [ ]:
import json
tweets = []
for line in open('../input/ina-data/INA_subtitles.json', 'r',encoding="utf-8"):
    tweets.append(json.loads(line))
    

In [ ]:
tweets[1]

In [ ]:
tweets[1]['segment']['text'][2]['event'][0]['startDate']

In [ ]:
tweets[1]['segment']['text'][2]['event'][0]['agent'][0]['identifier']

In [ ]:
%%time
import pandas as pd
import datetime
import csv

row = ['content', 'start', 'end','channel','lang','date','duration']
dataf=list()
with open('test2.csv', 'w') as myfile:
    df=pd.DataFrame()
    df[1]=row
    df.T.to_csv('test2.csv',mode='a',index=False,header=False)

    for i in range(len(tweets)):
        
        if i%10000==0:
            print(i)
        #row=[]
#         print(i)
#         date_time_str=tweets[i]['segment']['event'][0]['startDate']['$date']
#         row[1]=datetime.datetime.strptime(date_time_str, '%Y-%m-%dT%H:%M:%S.%f+0000').time()
#         enddate=tweets[i]['segment']['event'][0]['endDate']['$date']
#         row[2]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S.%f+0000').time()
#         row[5]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S.%f+0000').date()
        
        for j in range(len(tweets[i]['segment']['text'])):
            date_time_str=tweets[i]['segment']['text'][j]['event'][0]['startDate']
            row[1]=datetime.datetime.strptime(date_time_str, '%Y-%m-%dT%H:%M:%S,%f').time()
            enddate=tweets[i]['segment']['text'][j]['event'][0]['endDate']
            row[2]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S,%f').time()
            row[0]=tweets[i]['segment']['text'][j]['value']
            row[3]=tweets[i]['segment']['text'][j]['event'][0]['agent'][0]['identifier']
            row[4]=tweets[i]['segment']['text'][j]['lang']
            row[5]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S,%f').date()
            row[6]=(datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S,%f')-datetime.datetime.strptime(date_time_str, '%Y-%m-%dT%H:%M:%S,%f')).total_seconds()
#         print(df.T)
            dataf.append([row[0],row[1],row[2],row[3],row[4],row[5],row[6]])
            df[1]=row
    #         print(row)
        
#         print(df1)
#         df.T.to_csv('test2.csv',mode='a',index=False,header=False)

#         wr.writerow(row)


In [ ]:
dat= pd.DataFrame(dataf, columns=['content', 'start', 'end','channel','lang','date','duration'])
dat['start']

In [ ]:
dat.to_hdf('INA_subt.hdf', key='abc')


In [ ]:
dat


In [ ]:
# import pandas as pd
# data=pd.read_csv('../input/asr-out/test2.csv')

In [ ]:
# data['date'][0]

In [ ]:
# list('AB')

In [31]:
import pandas as pd
ground_truth = pd.read_hdf('../input/updated-data/pa_upda.hdf')
asr_out=pd.read_hdf('../input/updated-data/INA_subt.hdf')

In [32]:
ground_truth.head()

content       ...                   start
0  Flash avec Maxime David ce n'est pas un coup d...       ...         02:00:06.369000
1  Alors à tous , bonjour Élisabeth bonjour Alain...       ...         02:03:34.619000
2  Alors , en souhaitant le meilleur pour cette l...       ...         02:05:14.550000
3  Eh bien Alain Bourse vrai Éric Bustos , direct...       ...         02:05:21.119000
4  Quand il pas voilà je devenais , méchant , vio...       ...         02:06:17.260000

[5 rows x 10 columns]

In [33]:
ground_truth_=ground_truth.sort_values(by='start', ascending=False)[['content','date','duration','start','end','dataset']]


In [34]:
asr_out_=asr_out.sort_values(by='start', ascending=True)[['content','date','duration','start','end','channel']]


In [35]:
diff_chan_gt=ground_truth['dataset'].unique()
diff_chan_gt

array(['fit', 'fcr', 'fr2'], dtype=object)

In [36]:
diff_chan_asr=asr_out_['channel'].unique()
diff_chan_asr

array(['FR2', 'TF1', 'FR5', 'M6', 'FR3', 'ART', 'C+'], dtype=object)

In [37]:
time_gr=ground_truth_['start'].values.tolist()
time_gr.sort()

In [38]:

asr_out_.where(asr_out_['channel']=='FR2').dropna()

content   ...   channel
76081  I think of you I haven't slept I think I do Bu...   ...       FR2
47029  L'Etat doit intervenir dans la famille parce q...   ...       FR2
10114  La question importante de ce traité, c'est cet...   ...       FR2
18722  C'est sûr que dans les contes de fées, on met ...   ...       FR2
65263  Oui, mais parmi les jeunes, il y a surtout des...   ...       FR2
55727  Il va y avoir un long-métrage sur cet épisode....   ...       FR2
65264         Est-ce que c'est de la faute de l'Europe?    ...       FR2
63068             Bonjour. Vous en avez de quel style ?    ...       FR2
63069  Je vous envoie une capsule. Sonnerie. Un insta...   ...       FR2
65265  Ces mêmes jeunes se sont totalement abstenus d...   ...       FR2
55728          Ce sera un long-métrage pour le cinéma ?    ...       FR2
55729  Non. Ce sera un téléfilm pour France2 avant le...   ...       FR2
73482                                               ...    ...       FR2
47030  Le couple de la famille et de l'Etat est un co...   ...       FR2
63070  Hide et Mayumi Sakamoto sont mariés depuis 15 ...   ...       FR2
63071  J'ai tellement hâte d'être touchée. Mais ça fa...   ...       FR2
47031  Ce sera le mot de la fin. Je vous remercie d'a...   ...       FR2
73483  Bonjour, bonjour, bonjour, bonjour ! Ca va ? T...   ...       FR2
10115  Pierre Moscovici, des multinationales pourront...   ...       FR2
73484                                        SA PLACE !    ...       FR2
73485                  La place du champion, Christian.    ...       FR2
73486                                   Bonjour à tous.    ...       FR2
63072                                      C'est vrai ?    ...       FR2
63073  Hum, hum. Mais ma peau n'est vraiment pas bell...   ...       FR2
73487                                    Ca va, papou ?    ...       FR2
73488                                        Très bien.    ...       FR2
73489       Vos petits-enfants vous appellent comme ça.    ...       FR2
73490                       C'est ça, il y a Charles...    ...       FR2
63074                                  Ca te fait mal ?    ...       FR2
73491                               J'aime bien le ton.    ...       FR2
...                                                  ...   ...       ...
18717                               Dans la vraie vie ?    ...       FR2
18718  Dans la vraie vie. Et là, je suis dans l'avion...   ...       FR2
65259  Cela va être compliqué! Jean-François Copé n'a...   ...       FR2
47023  Ils disent qu'ils ont moins de chances de divo...   ...       FR2
55719  Oui. Il y a l'histoire de Jacques Mayol. Il a ...   ...       FR2
10110              Vous avez déjà cédé face à la NSA...    ...       FR2
47024  Ce n'est peut-être pas ça qui va améliorer ce ...   ...       FR2
55720  Aujourd'hui, le record, en piscine, c'est 11mn...   ...       FR2
10111  José Bové, êtes-vous hostile à ce transatlanti...   ...       FR2
10112  Je ne peux pas accepter ce qui vient d'être di...   ...       FR2
65260  On parle d'une direction provisoire qui serait...   ...       FR2
65261  Je pense que, malheureusement, nous ne sommes ...   ...       FR2
47025  J'aime bien l'anarchisme de Jean-Didier, que j...   ...       FR2
65262  Emmanuelle Cosse, une dernière remarque... 30%...   ...       FR2
55721  Ca ne vous emmerde pas d'avoir un père qui a l...   ...       FR2
55722  Non. Parce que j'ai réussi à tuer le père en s...   ...       FR2
10113     Comme toi qui sors ta casquette écologique...    ...       FR2
63065  Ils ont l'air si heureux. Tu veux avoir un enf...   ...       FR2
18719                                 C'était la bonne.    ...       FR2
18720  Et peu de temps après, Jennifer Lopez a rompu ...   ...       FR2
55723                             Un mot sur le livre ?    ...       FR2
55724  C'est un livre très agréable à feuilleter. On ...   ...       FR2
18721  On a raconté cet itinéraire jusqu'à ce moment-...   ...       FR2
63066                    Un enfant

In [39]:
ground_fr=ground_truth_.where(ground_truth_['dataset']=='fr2' ).dropna()


In [ ]:
# !python3 -m spacy download fr_core_news_sm


In [ ]:
# from __future__ import print_function

# import plac
# from spacy.attrs import ORTH
# import io

# def main(text_loc):
#     with io.open(text_loc, 'r', encoding='utf8') as file_:
#         text = file_.read()
#     nlp = English()
#     doc = nlp(text)

#     counts = doc.count_by(ORTH)
#     print(len(counts))
#     for word_id, count in sorted(counts.items(), reverse=True, key=lambda item: item[1]):
#         print(count, nlp.vocab.strings[word_id])

# if __name__ == '__main__':
#     plac.call(main)

<h3>Text Preprocessing with spacy</h3>

In [ ]:
# from __future__ import print_function

# import plac
# from spacy.attrs import ORTH
# import spacy
# import fr_core_news_sm
# from spacy.lang.fr.examples import sentences 
# nlp = fr_core_news_sm.load()
# from spacy import displacy
# # st=' '
# # st=st.join(grou[0])
# index=list(set(ground_fr.index))
# for i in range(10):
#     doc=nlp(ground_fr['content'][index [i]])
#     counts = doc.count_by(ORTH)
#     print(len(counts))
#     for word_id, count in sorted(counts.items(), reverse=True, key=lambda item: item[1]):
#         print(count, nlp.vocab.strings[word_id])
#     displacy.render(nlp(ground_fr['content'][index [i]]), jupyter=True, style='ent')


In [40]:
ground_truth_['hour_start']=[d.hour for d in ground_truth_['start']]
asr_out_['hour_start']=[d.hour for d in asr_out_['start']]

In [41]:
asr_out_['hour_start'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [42]:
ground_truth_['hour_start'].unique()

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1,  0])

In [43]:
ground_truth_=ground_truth_.reset_index()
asr_out_=asr_out_.reset_index()

In [45]:
ground_truth_.head()

index    ...     hour_start
0  105636    ...             23
1  105635    ...             23
2   17930    ...             23
3   16755    ...             23
4  105634    ...             23

[5 rows x 8 columns]

In [46]:
# ground_truth_['content']=ground_truth_['content']+ground_truth_['index'].map(str)+" "
# asr_out_['content']=asr_out_['content']+asr_out_['index'].map(str)+" "


In [48]:
ground_truth_['content']=ground_truth_['content']+" "
asr_out_['content']=asr_out_['content']+" "

In [49]:
grouped_df=ground_truth_.groupby(by=['date'])
tab_gr_date={}
for key, item in grouped_df:
    tab_gr_date[key]=item
    gr=tab_gr_date[key].groupby(by=['dataset'])
    t={}
    for k, i in gr:
        t[k]=i
    tab_gr_date[key]=t

grouped_df=asr_out_.groupby(by=['date'])
tab_asr_date={}
for key, item in grouped_df:
    tab_asr_date[key]=item
    gr=tab_asr_date[key].groupby(by=['channel'])
    t={}
    for k, i in gr:
        t[k]=i
    tab_asr_date[key]=t

In [ ]:
# import datetime
# tab_gr_date[datetime.date(2014, 5, 19)]['fr2'].sort_values(by='start',ascending=True).content.sum()

In [ ]:
# tab_asr_date[datetime.date(2014, 5, 19)]['FR2'].sort_values(by='start',ascending=True).content.sum()

In [ ]:
# import datetime
# prepdata_asr=tab_asr_date[datetime.date(2014, 5, 21)]['FR2'].sort_values(by='start',ascending=True)
# I=prepdata_asr.where(prepdata_asr['start']>datetime.time(23, 40,0)).dropna()
# I.drop(columns=['duration','end','channel','date'])


In [50]:
ground_truth_19=tab_gr_date[datetime.date(2014, 5, 19)]['fr2'].sort_values(by='start',ascending=True)

In [51]:
asr_out_19=tab_asr_date[datetime.date(2014, 5, 19)]['FR2'].sort_values(by='start')

data preprocessing

In [ ]:
from __future__ import print_function

import plac
from spacy.attrs import ORTH
import spacy
import fr_core_news_sm
from spacy.lang.fr.examples import sentences 
nlp = fr_core_news_sm.load()
from spacy import displacy
# Clean text before feeding it to spaCy
punctuations = '!"#$%&\'()*+,-/:;<=>?@[\\]^_`{|}~'
# Define function to cleanup text by removing personal pronouns, stopwords, and puncuation
def cleanup_text(docs, logging=False):
    texts = []
    doc = nlp(docs, disable=['parser', 'ner'])
    tokens = [tok.lemma_.lower().strip() for tok in doc if tok.lemma_ != '-PRON-']
    tokens = [tok for tok in tokens if tok not in punctuations]
    tokens = ' '.join(tokens)
    texts.append(tokens)
    return pd.Series(texts)


ground_truth_19['content_Cleaned'] = ground_truth_['content'].apply(lambda x: cleanup_text(x, False))
asr_out_19['content_Cleaned'] = asr_out_19['content'].apply(lambda x: cleanup_text(x, False))

In [ ]:
asr_out_19_h_6=asr_out_19.where(asr_out_19['hour_start']==6).dropna()
ground_truth_19_h_6=ground_truth_19.where(ground_truth_19['hour_start']==6).dropna()

In [ ]:
ground_truth_19_h_6.head()

In [ ]:
asr_out_19_h_6.head()

In [ ]:
!pip install fuzzywuzzy
!pip install python-Levenshtein

In [ ]:
# index1=ground_truth_19.index
ground_truth_19.loc[98310]

**TEXT MATCHING 
**

In [ ]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
# st1=ground_truth_19.where((ground_truth_19['index']==57867)).dropna()['content_asr_out_19.where((asr_out_19['index']==10003)).dropna()['content_Cleaned']).item()Cleaned'].item()
# st2=asr_out_19.where((asr_out_19['index']==10003)).dropna()['content_Cleaned'].item()
score=[]
index1=ground_truth_19.index
index2=asr_out_19.index
for i in range(len(index1)):
    for j in range(len(index2)):
        st1=ground_truth_19.loc[index1[i]]['content_Cleaned']
        st2=asr_out_19.loc[index2[j]]['content_Cleaned']
        score.append([index1[i],index2[j],fuzz.ratio(st1,st2)])

matched_text= pd.DataFrame(score, columns=['index_gt','index_asr','score'])


104182, 10114

In [ ]:
matched_text= pd.DataFrame(score, columns=['index_gt','index_asr','score'])


In [ ]:
ground_truth_19.loc[104182]['content_Cleaned']

In [ ]:

asr_out_19.loc[10175]['content_Cleaned']

In [ ]:
matched_text.where(matched_text.score>40).dropna()

In [ ]:
# doc1=nlp(asr_out_19_h_6)
# doc2=nlp(ground_truth_19_h_6)
# counts1 = doc1.count_by(ORTH)
# counts2=doc2.count_by(ORTH)
# print(len(counts1))
# s1=[]
# s2=[]
# for word_id, count in sorted(counts1.items(), reverse=True, key=lambda item: item[1]):
#    s1.append([count, nlp.vocab.strings[word_id]])
# for word_id, count in sorted(counts2.items(), reverse=True, key=lambda item: item[1]):
#     s2.append([count, nlp.vocab.strings[word_id]])

# s1_=pd.DataFrame(s1,columns=['count','word'])
# s2_=pd.DataFrame(s2,columns=['count','word'])


In [55]:
ground_truth_19.where((ground_truth_19['index']==98310)).dropna()

index    ...     hour_start
51  98310.0    ...           23.0

[1 rows x 8 columns]

In [56]:
asr_out_19.where((asr_out_19['index']==10114)).dropna()

index    ...     hour_start
10  10114.0    ...            0.0

[1 rows x 8 columns]

In [57]:
ground_truth_19.where((ground_truth_19['index']==70460)|(ground_truth_19['index']==70461)|(ground_truth_19['index']==70462)).dropna()

index    ...     hour_start
53791  70460.0    ...           12.0
53748  70461.0    ...           12.0
53728  70462.0    ...           12.0

[3 rows x 8 columns]

In [58]:
asr_out_19.where((asr_out_19['index']==8135)|(asr_out_19['index']==8136)|(asr_out_19['index']==8137)|(asr_out_19['index']==8138)|(asr_out_19['index']==8139)|(asr_out_19['index']==8140)|(asr_out_19['index']==8141)|(asr_out_19['index']==8141)|(asr_out_19['index']==8142)|(asr_out_19['index']==8143)|(asr_out_19['index']==8145)|(asr_out_19['index']==8146)|(asr_out_19['index']==8147)|(asr_out_19['index']==8148)).dropna()

index    ...     hour_start
496  8135.0    ...            0.0
526  8136.0    ...            0.0
545  8137.0    ...            0.0
561  8138.0    ...            0.0
587  8139.0    ...            0.0
597  8140.0    ...            0.0
720  8141.0    ...            0.0
741  8142.0    ...            0.0
766  8143.0    ...            0.0
794  8145.0    ...            0.0
838  8146.0    ...            0.0
884  8147.0    ...            0.0
922  8148.0    ...            0.0

[13 rows x 8 columns]

In [59]:
# ground_truth_19.where((ground_truth_19['index']==57867)).dropna()['content_Cleaned'].item()

In [60]:
asr_out_19.where((asr_out_19['index']==10003)).dropna()

index    ...     hour_start
76824  10003.0    ...           20.0

[1 rows x 8 columns]

In [61]:
asr_out_19.where((asr_out_19['index']==9871)).dropna()

index    ...     hour_start
71000  9871.0    ...           20.0

[1 rows x 8 columns]

In [62]:
ground_truth_19.where((ground_truth_19['index']==86075)).dropna()

index    ...     hour_start
17360  86075.0    ...           20.0

[1 rows x 8 columns]

In [63]:
ground_truth_19.where((ground_truth_19['index']==86077)).dropna()

index    ...     hour_start
17345  86077.0    ...           20.0

[1 rows x 8 columns]

In [64]:
asr_out_19.where((asr_out_19['index']==9872)).dropna()

index    ...     hour_start
71039  9872.0    ...           20.0

[1 rows x 8 columns]

ground truth:<br>
10114 'La question importante de ce traité, c\'est cet article qui permettrait aux entreprises d\'attaquer les Etats ou l\'Union européenne si les règles de ces institutions vont contre l\'intérêt des investisseurs. C\'est le coeur de l\'accord. Si cet accord se met en place, on prend un exemple très simple, celui du gaz de schiste. Un pays comme la Pologne est pour le gaz de schiste... Si demain l\'accord est signé, des investisseurs pourront attaquer le nouveau gouvernement parce qu\'il aura interdit la fracturation. Ce sont les règles démocratiques qui sont en cause. On a eu le problème sont les règles démocratiques qui sont en cause. On a eu le problème avec Veolia. Veolia a attaqué le gouvernement égyptien parce qu\'il avait augmenté les salaires des personnes qui travaillaient sur ses chantiers. C\'est dramatique. L\'argument qu\'il n\'y a que des règles non tarifaires, il y a aussi des conséquences dramatiques pour l\'élevage européen. J\'ai regardé les documents sur les barèmes tarifaires, ça va être une catastrophe. L\'ensemble de l\'élevage à l\'herbe européen va être fracassé si on fait entrer toute cette viande sur le marché. <br>
<br>
<br>ASR:<br>
98310 Voilà parole point presse , le Tour de France , je crois que la question hein nous avons importante dans ce traité , et ça a été soulevée , c'est cet article qui permettrait aux entreprises d'attaquer des États où l'Union européenne si les règles de ces pays de ces institutions vont contre l'intérêt des investisseurs , ça c'est le coeur de l'accord parce que si cet accord se met en place en proie un exemple très simple : celui de Gaz de un pays comme la Pologne , pour l'instant , farouchement pour le gaz de schiste , ça va changer , parce que la population manifeste le cinéma , il change de gouvernement et que l'accord est signé des investisseurs sont venus et ils disent : nous on veut , hé bien ils pourront attaquer le nouveau gouvernement parce que il y aura interdit la facturation , c'est ce qui se passe entre les États-Unis et le Canada , et donc ça , ça pose un problème majeur , parce que ce sont les règles démocratiques qui sont en cause et , malgré tout , je veux revenir aussi , puis on a eu le problème avec Veolia Veolia a attaqué le gouvernement égyptien en deux mille deux deux mille trois parce qu'il avait augmenté les salaires des .<br>
<br>
ground truth:<br>
Nagui : 8135 3 victoires. Vous étiez directrice d\'école maternelle pendant combien de mois ? <br>
Danielle : Pendant 30 ans. <br>
8136 Nagui : On approche de 360 mois. C\'est dingue.
<br>8137 Danielle : En plus, ça fait 20 ans que je suis à la retraite. <br>
8138 Nagui : Vous ne les faites pas. Les filles peuvent avoir peur des serpents, des araignées ? De quoi ? Des cons dans le métro ? Des crocodiles ? Où tu as vu des crocodiles ? <br>
8139 J\'ai peur des crocodiles. <br>
8140 Nagui : Je comprends. Vous avez déjà vu un crocodile ? <br>
8141 Je n\'avais pas compris la question. <br>
8144 Nagui : C\'était quoi, la question ? Vous habitez dans quel coin ? <br>
8145 La honte ! <br>
8146 Nagui : Vous évitez à la Honte ? Allez, bisous. Un crocodile ! Vous, vous avez peur de quoi ? <br>
8146
8147 Danielle : Des escaliers. C\'est depuis que j\'ai dévalé un escalier chez mon fils et que je me suis cassé la cheville. J\'évite de descendre les escaliers. <br>
8148 Nagui : C\'est une championne qui, à chaque début d\'émission, descend les escaliers. C\'est beau, respect. Voici celles et ceux qui veulent votre place : Carole, Bastien, Nathalie, Philippe, Véronique, Claude ! Un crocodile ! Et des cadeaux. 
<br> 
10120Je viens de répondre de la manière la plus claire. L\'Europe doit être capable de défendre ses intérêts. 

<br>
<br>ASR:<br>
70460 3 victoires 3100 euros vous dites si ils disaient qu'ils étaient en maternelle pendant 30 ans mois 30 ans , 30 ans , puis on les a , on avait 360 moi c'est pareil , mieux ça fait vingt ans que je suis à la retraite , en plus , j'ai fait une retraite anticipée , vous les faites pas merci , vous avez 20 ans de ne vous de fait penser , vous vous êtes vous avez peur alors ici sans avoir peur des quoi serpents de vingt-sept ans de ça prend ça pour vous alliez vous êtes vous alliez vous attendez quoi qu'on en métro ou à très bien oui , mais pas de quoi non c'est vrai c'est c'est c'est à vous , il est temps de quoi de crocodiles ou d'avenir .<br>
70461 Trop rigides lors des crocodiles sur un . <br>
70462 Je vois crocodiles mais je crois moins les des viandes , des PDG de groupes , c'était quoi la question si vous habitez dans quel coin aux yeux bon où il y a des crocodiles dans le pays vous habitez à l'à la gare est .<br><br>
<br><br>
ground truth:<br>
63312 Des intempéries frappent les Balkans depuis 3 jours et ont déjà fait 44 morts et des milliers de sinistrés. Le bilan pourrait encore s\'alourdir selon les autorités. En plus des inondations, les pluies intenses provoquent des coulées de boue et des glissements de terrain qui entraînent l\'effondrement des maisons. Plusieurs pays de l\'Union européenne ont dépêché des dizaines de secouristes et des médicaments ainsi que des vivres. Direction le Festival de Cannes. Le festival bat son plein. Hier, la montée des marches a été marquée par la présence de T.Lee Jones, présent en tant que réalisateur. 

<br>GRound truth:<br>

9871 Notre envoyé spécial Renaud Bernard se trouve à une centaine de kilomètres de Belgrade, sur les rives de la Sava, affluent du Danube qui continue à monter. Nous venons de recevoir son témoignage, on l\'écoute : 

<br><br> ASR <br>
Notre envoyé spécial , Renaud Bernard se trouve à une centaine de kilomètres de Belgrade sur les rives de la Save affluent du Danube qui continue à monter , nous venons de recevoir son témoignage .86075

<br>GRound truth:<br>

9872 Renaud Bernard : La Serbie mène l\'offensive du sable pour bloquer l\'eau. Toute son armée est mobilisée mais également des volontaires. Ils remplissent des centaines de milliers de sacs de sable. On parle même de millions de sacs de sable pour faire rempart contre l\'offensive de l\'eau. Cela se passe en ce moment. Nous sommes à 120 km à l\'ouest de Belgrade, le fleuve Save est en train de monter, l\'onde de crue se déplace. D\'où ces dizaines de volontaires qui viennent de partout dans le pays. Ce sont des enseignants, des fonctionnaires, des étudiants, ils sont là pour poser ces sacs de sable sur des dizaines de kilomètres. Demain ou après-demain, elle risque de déborder à Belgrade.  

<br><br> ASR <br>
86077 La Serbie mène en ce moment , l'offensive du sable pour bloquer celle de avec toute son armée , qui a mobilisé , mais également des volontaires qui remplissent des centaines de milliers de sacs de sable , on parle même 2 millions de sacs de sable pour faire rempart contre l'offensive de l'eau , cela se passe en ce moment nous sommes achat à 120 kilomètres à l'ouest de Belgrade et le Vlaams arabe est en train de monter . Londres de crue les plaçait une va avec tous ces dizaines de volontaires qui viennent de partout dans le pays , ce sont des enseignants , ce sont des fonctionnaires , ce sont des étudiants , ce sont les commerçants , ils sont là pour poser ses sacs de sable sur des dizaines de kilomètres parce que l'eau monte aujourd'hui ici et demain .