In [0]:
# import pandas as pd
# sub=pd.read_csv('../input/pa_subtitles.csv')
# sub

In [0]:
# len(sub)
# 105637/7

In [0]:
# %%time
# import datetime
# for i in range(sub.shape[0]//7):
#     if i%100==0:
#         print(i)
#     for j in range(7):
#         sub['start'][i+j*15091] = datetime.datetime.strptime(sub['start'][i+j*15091], '%H:%M:%S.%f').time() 
#         sub['end'][i+j*15091]=datetime.datetime.strptime(sub['end'][i+j*15091], '%H:%M:%S.%f').time() 
#         sub['date'][i+j*15091]=datetime.datetime.strptime(sub['date'][i+j*15091], '%Y-%m-%d').date()

# sub.to_csv('pa_subtitles.csv',mode='a',index=False,header=False)


In [0]:
import json
tweets = []
for line in open('../input/ina-data/INA_subtitles.json', 'r',encoding="utf-8"):
    tweets.append(json.loads(line))
    

In [0]:
tweets[1]

In [0]:
tweets[1]['segment']['text'][2]['event'][0]['startDate']

In [0]:
tweets[1]['segment']['text'][2]['event'][0]['agent'][0]['identifier']

In [0]:
%%time
import pandas as pd
import datetime
import csv

row = ['content', 'start', 'end','channel','lang','date','duration']
dataf=list()
with open('test2.csv', 'w') as myfile:
    df=pd.DataFrame()
    df[1]=row
    df.T.to_csv('test2.csv',mode='a',index=False,header=False)

    for i in range(len(tweets)):
        
        if i%10000==0:
            print(i)
        #row=[]
#         print(i)
#         date_time_str=tweets[i]['segment']['event'][0]['startDate']['$date']
#         row[1]=datetime.datetime.strptime(date_time_str, '%Y-%m-%dT%H:%M:%S.%f+0000').time()
#         enddate=tweets[i]['segment']['event'][0]['endDate']['$date']
#         row[2]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S.%f+0000').time()
#         row[5]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S.%f+0000').date()
        
        for j in range(len(tweets[i]['segment']['text'])):
            date_time_str=tweets[i]['segment']['text'][j]['event'][0]['startDate']
            row[1]=datetime.datetime.strptime(date_time_str, '%Y-%m-%dT%H:%M:%S,%f').time()
            enddate=tweets[i]['segment']['text'][j]['event'][0]['endDate']
            row[2]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S,%f').time()
            row[0]=tweets[i]['segment']['text'][j]['value']
            row[3]=tweets[i]['segment']['text'][j]['event'][0]['agent'][0]['identifier']
            row[4]=tweets[i]['segment']['text'][j]['lang']
            row[5]=datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S,%f').date()
            row[6]=(datetime.datetime.strptime(enddate, '%Y-%m-%dT%H:%M:%S,%f')-datetime.datetime.strptime(date_time_str, '%Y-%m-%dT%H:%M:%S,%f')).total_seconds()
#         print(df.T)
            dataf.append([row[0],row[1],row[2],row[3],row[4],row[5],row[6]])
            df[1]=row
    #         print(row)
        
#         print(df1)
#         df.T.to_csv('test2.csv',mode='a',index=False,header=False)

#         wr.writerow(row)


In [0]:
dat= pd.DataFrame(dataf, columns=['content', 'start', 'end','channel','lang','date','duration'])
dat['start']

In [0]:
dat.to_hdf('INA_subt.hdf', key='abc')


In [0]:
dat


In [0]:
# import pandas as pd
# data=pd.read_csv('../input/asr-out/test2.csv')

In [0]:
# data['date'][0]

In [0]:
# list('AB')

In [2]:
import pandas as pd
ground_truth = pd.read_hdf('gdrive/My Drive/eurecom/Aloui_NER-MeMAD/code/data/pa_upda.hdf')
asr_out=pd.read_hdf('gdrive/My Drive/eurecom/Aloui_NER-MeMAD/code/data/INA_subt.hdf')

FileNotFoundError: ignored

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
with open('/gdrive/My Drive/foo.txt', 'w') as f:
  f.write('Hello Google Drive!')
!cat '/gdrive/My Drive/foo.txt'

In [0]:
ground_truth.head()

In [0]:
ground_truth_=ground_truth.sort_values(by='start', ascending=False)[['content','date','duration','start','end','dataset']]
ground_truth_

In [0]:
asr_out_=asr_out.sort_values(by='start', ascending=True)[['content','date','duration','start','end','channel']]
asr_out_

In [0]:
diff_chan_gt=ground_truth['dataset'].unique()
diff_chan_gt

In [0]:
diff_chan_asr=asr_out_['channel'].unique()
diff_chan_asr

In [0]:
time_gr=ground_truth_['start'].values.tolist()
time_gr.sort()

In [0]:

asr_out_.where(asr_out_['channel']=='FR2').dropna()

In [0]:
ground_fr=ground_truth_.where(ground_truth_['dataset']=='fr2' ).dropna()


<h1>named entity recognition with spacy </h1>

In [0]:
!python3 -m spacy download fr_core_news_sm


In [0]:
import spacy
import fr_core_news_sm
from spacy.lang.fr.examples import sentences 
nlp = fr_core_news_sm.load()
from spacy import displacy
# st=' '
# st=st.join(grou[0])
index=list(set(ground_fr.index))
for i in range(100):
    
    displacy.render(nlp(ground_fr['content'][index [i]]), jupyter=True, style='ent')


In [0]:
ground_truth_=ground_truth_.reset_index()
asr_out_=asr_out_.reset_index()

In [0]:
ground_truth_

In [0]:
ground_truth_['content']=ground_truth_['content']+ground_truth_['index'].map(str)+" "
asr_out_['content']=asr_out_['content']+asr_out_['index'].map(str)+" "


In [0]:
grouped_df=ground_truth_.groupby(by=['date'])
tab_gr_date={}
for key, item in grouped_df:
    tab_gr_date[key]=item
    gr=tab_gr_date[key].groupby(by=['dataset'])
    t={}
    for k, i in gr:
        t[k]=i
    tab_gr_date[key]=t

grouped_df=asr_out_.groupby(by=['date'])
tab_asr_date={}
for key, item in grouped_df:
    tab_asr_date[key]=item
    gr=tab_asr_date[key].groupby(by=['channel'])
    t={}
    for k, i in gr:
        t[k]=i
    tab_asr_date[key]=t

In [0]:
# import datetime
# tab_gr_date[datetime.date(2014, 5, 19)]['fr2'].sort_values(by='start',ascending=True).content.sum()

In [0]:
# tab_asr_date[datetime.date(2014, 5, 19)]['FR2'].sort_values(by='start',ascending=True).content.sum()

In [0]:
import datetime
prepdata_asr=tab_asr_date[datetime.date(2014, 5, 21)]['FR2'].sort_values(by='start',ascending=True)
I=prepdata_asr.where(prepdata_asr['start']>datetime.time(23, 40,0)).dropna()
I.drop(columns=['duration','end','channel','date'])


In [0]:
ground_truth_19=tab_gr_date[datetime.date(2014, 5, 19)]['fr2'].sort_values(by='start',ascending=True)

In [0]:
asr_out_19=tab_asr_date[datetime.date(2014, 5, 19)]['FR2'].sort_values(by='start')

In [0]:
asr_out_19

In [0]:
ground_truth_19.where((ground_truth_19['index']==98310)).dropna()

index   ...   dataset
51  98310.0   ...       fr2

[1 rows x 7 columns]

In [0]:
asr_out_19.where((asr_out_19['index']==10114)).dropna()

index   ...   channel
10  10114.0   ...       FR2

[1 rows x 7 columns]

In [0]:
ground_truth_19.where((ground_truth_19['index']==70460)|(ground_truth_19['index']==70461)|(ground_truth_19['index']==70462)).dropna()

index   ...   dataset
53791  70460.0   ...       fr2
53748  70461.0   ...       fr2
53728  70462.0   ...       fr2

[3 rows x 7 columns]

In [0]:
asr_out_19.where((asr_out_19['index']==8135)|(asr_out_19['index']==8136)|(asr_out_19['index']==8137)|(asr_out_19['index']==8138)|(asr_out_19['index']==8139)|(asr_out_19['index']==8140)|(asr_out_19['index']==8141)|(asr_out_19['index']==8141)|(asr_out_19['index']==8142)|(asr_out_19['index']==8143)|(asr_out_19['index']==8145)|(asr_out_19['index']==8146)|(asr_out_19['index']==8147)|(asr_out_19['index']==8148)).dropna()

index   ...   channel
496  8135.0   ...       FR2
526  8136.0   ...       FR2
545  8137.0   ...       FR2
561  8138.0   ...       FR2
587  8139.0   ...       FR2
597  8140.0   ...       FR2
720  8141.0   ...       FR2
741  8142.0   ...       FR2
766  8143.0   ...       FR2
794  8145.0   ...       FR2
838  8146.0   ...       FR2
884  8147.0   ...       FR2
922  8148.0   ...       FR2

[13 rows x 7 columns]

In [0]:
ground_truth_19.where((ground_truth_19['index']==57867)).dropna()

In [0]:
asr_out_19.where((asr_out_19['index']==10003)).dropna()

In [0]:
asr_out_19.where((asr_out_19['index']==9871)).dropna()

In [0]:
ground_truth_19.where((ground_truth_19['index']==86075)).dropna()

In [0]:
ground_truth_19.where((ground_truth_19['index']==86077)).dropna()

index   ...   dataset
17345  86077.0   ...       fr2

[1 rows x 7 columns]

In [0]:
asr_out_19.where((asr_out_19['index']==9872)).dropna()

index   ...   channel
71039  9872.0   ...       FR2

[1 rows x 7 columns]

ground truth:<br>
10114 'La question importante de ce traité, c\'est cet article qui permettrait aux entreprises d\'attaquer les Etats ou l\'Union européenne si les règles de ces institutions vont contre l\'intérêt des investisseurs. C\'est le coeur de l\'accord. Si cet accord se met en place, on prend un exemple très simple, celui du gaz de schiste. Un pays comme la Pologne est pour le gaz de schiste... Si demain l\'accord est signé, des investisseurs pourront attaquer le nouveau gouvernement parce qu\'il aura interdit la fracturation. Ce sont les règles démocratiques qui sont en cause. On a eu le problème sont les règles démocratiques qui sont en cause. On a eu le problème avec Veolia. Veolia a attaqué le gouvernement égyptien parce qu\'il avait augmenté les salaires des personnes qui travaillaient sur ses chantiers. C\'est dramatique. L\'argument qu\'il n\'y a que des règles non tarifaires, il y a aussi des conséquences dramatiques pour l\'élevage européen. J\'ai regardé les documents sur les barèmes tarifaires, ça va être une catastrophe. L\'ensemble de l\'élevage à l\'herbe européen va être fracassé si on fait entrer toute cette viande sur le marché. <br>
<br>
<br>ASR:<br>
98310 Voilà parole point presse , le Tour de France , je crois que la question hein nous avons importante dans ce traité , et ça a été soulevée , c'est cet article qui permettrait aux entreprises d'attaquer des États où l'Union européenne si les règles de ces pays de ces institutions vont contre l'intérêt des investisseurs , ça c'est le coeur de l'accord parce que si cet accord se met en place en proie un exemple très simple : celui de Gaz de un pays comme la Pologne , pour l'instant , farouchement pour le gaz de schiste , ça va changer , parce que la population manifeste le cinéma , il change de gouvernement et que l'accord est signé des investisseurs sont venus et ils disent : nous on veut , hé bien ils pourront attaquer le nouveau gouvernement parce que il y aura interdit la facturation , c'est ce qui se passe entre les États-Unis et le Canada , et donc ça , ça pose un problème majeur , parce que ce sont les règles démocratiques qui sont en cause et , malgré tout , je veux revenir aussi , puis on a eu le problème avec Veolia Veolia a attaqué le gouvernement égyptien en deux mille deux deux mille trois parce qu'il avait augmenté les salaires des .<br>
<br>
ground truth:<br>
Nagui : 8135 3 victoires. Vous étiez directrice d\'école maternelle pendant combien de mois ? <br>
Danielle : Pendant 30 ans. <br>
8136 Nagui : On approche de 360 mois. C\'est dingue.
<br>8137 Danielle : En plus, ça fait 20 ans que je suis à la retraite. <br>
8138 Nagui : Vous ne les faites pas. Les filles peuvent avoir peur des serpents, des araignées ? De quoi ? Des cons dans le métro ? Des crocodiles ? Où tu as vu des crocodiles ? <br>
8139 J\'ai peur des crocodiles. <br>
8140 Nagui : Je comprends. Vous avez déjà vu un crocodile ? <br>
8141 Je n\'avais pas compris la question. <br>
8144 Nagui : C\'était quoi, la question ? Vous habitez dans quel coin ? <br>
8145 La honte ! <br>
8146 Nagui : Vous évitez à la Honte ? Allez, bisous. Un crocodile ! Vous, vous avez peur de quoi ? <br>
8146
8147 Danielle : Des escaliers. C\'est depuis que j\'ai dévalé un escalier chez mon fils et que je me suis cassé la cheville. J\'évite de descendre les escaliers. <br>
8148 Nagui : C\'est une championne qui, à chaque début d\'émission, descend les escaliers. C\'est beau, respect. Voici celles et ceux qui veulent votre place : Carole, Bastien, Nathalie, Philippe, Véronique, Claude ! Un crocodile ! Et des cadeaux. 
<br> 
10120Je viens de répondre de la manière la plus claire. L\'Europe doit être capable de défendre ses intérêts. 

<br>
<br>ASR:<br>
70460 3 victoires 3100 euros vous dites si ils disaient qu'ils étaient en maternelle pendant 30 ans mois 30 ans , 30 ans , puis on les a , on avait 360 moi c'est pareil , mieux ça fait vingt ans que je suis à la retraite , en plus , j'ai fait une retraite anticipée , vous les faites pas merci , vous avez 20 ans de ne vous de fait penser , vous vous êtes vous avez peur alors ici sans avoir peur des quoi serpents de vingt-sept ans de ça prend ça pour vous alliez vous êtes vous alliez vous attendez quoi qu'on en métro ou à très bien oui , mais pas de quoi non c'est vrai c'est c'est c'est à vous , il est temps de quoi de crocodiles ou d'avenir .<br>
70461 Trop rigides lors des crocodiles sur un . <br>
70462 Je vois crocodiles mais je crois moins les des viandes , des PDG de groupes , c'était quoi la question si vous habitez dans quel coin aux yeux bon où il y a des crocodiles dans le pays vous habitez à l'à la gare est .<br><br>
<br><br>
ground truth:<br>
63312 Des intempéries frappent les Balkans depuis 3 jours et ont déjà fait 44 morts et des milliers de sinistrés. Le bilan pourrait encore s\'alourdir selon les autorités. En plus des inondations, les pluies intenses provoquent des coulées de boue et des glissements de terrain qui entraînent l\'effondrement des maisons. Plusieurs pays de l\'Union européenne ont dépêché des dizaines de secouristes et des médicaments ainsi que des vivres. Direction le Festival de Cannes. Le festival bat son plein. Hier, la montée des marches a été marquée par la présence de T.Lee Jones, présent en tant que réalisateur. 

<br>GRound truth:<br>

9871 Notre envoyé spécial Renaud Bernard se trouve à une centaine de kilomètres de Belgrade, sur les rives de la Sava, affluent du Danube qui continue à monter. Nous venons de recevoir son témoignage, on l\'écoute : 

<br><br> ASR <br>
Notre envoyé spécial , Renaud Bernard se trouve à une centaine de kilomètres de Belgrade sur les rives de la Save affluent du Danube qui continue à monter , nous venons de recevoir son témoignage .86075

<br>GRound truth:<br>

9872 Renaud Bernard : La Serbie mène l\'offensive du sable pour bloquer l\'eau. Toute son armée est mobilisée mais également des volontaires. Ils remplissent des centaines de milliers de sacs de sable. On parle même de millions de sacs de sable pour faire rempart contre l\'offensive de l\'eau. Cela se passe en ce moment. Nous sommes à 120 km à l\'ouest de Belgrade, le fleuve Save est en train de monter, l\'onde de crue se déplace. D\'où ces dizaines de volontaires qui viennent de partout dans le pays. Ce sont des enseignants, des fonctionnaires, des étudiants, ils sont là pour poser ces sacs de sable sur des dizaines de kilomètres. Demain ou après-demain, elle risque de déborder à Belgrade.  

<br><br> ASR <br>
86077 La Serbie mène en ce moment , l'offensive du sable pour bloquer celle de avec toute son armée , qui a mobilisé , mais également des volontaires qui remplissent des centaines de milliers de sacs de sable , on parle même 2 millions de sacs de sable pour faire rempart contre l'offensive de l'eau , cela se passe en ce moment nous sommes achat à 120 kilomètres à l'ouest de Belgrade et le Vlaams arabe est en train de monter . Londres de crue les plaçait une va avec tous ces dizaines de volontaires qui viennent de partout dans le pays , ce sont des enseignants , ce sont des fonctionnaires , ce sont des étudiants , ce sont les commerçants , ils sont là pour poser ses sacs de sable sur des dizaines de kilomètres parce que l'eau monte aujourd'hui ici et demain .